"use client"
import './globals.css'
import localFont from '@next/font/local'
import { Provider } from "react-redux"
import { store } from './state/store'
import { ToastContainer } from "react-toastify"
import 'react-toastify/dist/ReactToastify.css'

const sahel = localFont({
  src: [{
    path: '../public/fonts/Sahel-Bold-FD.ttf',
    weight: '500',
    style:"bold"
  },
    {
      path: '../public/fonts/Sahel-FD.ttf',
      weight: '400',
      style:"normal"
    },
  ],
  variable: '--font-sahel'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={`${sahel.variable} font-sans bg-[#d6c7da]`}>
        <Provider store={store}>
        <ToastContainer style={{zIndex:9999}} />
          <div className='pr-6 pt-6 '>
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}
